use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.12 # Reduced from 0.45 to 0.20 for DDP compatibility #22 sec/iteration with .25 14B
vllm_tensor_parallel_size: 1
# vllm_max_model_len: 2048 # Apparently this is overriden by max_prompt_len + max_completion_len
vllm_enable_sleep_mode: true
output_dir: GRPO
learning_rate: 1e-04
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
max_prompt_length: 512
max_completion_length: 2048
num_generations: 4 # actually the number of generations that goes into advantage calculation
optim: adamw_8bit
num_train_epochs: 1
bf16: true
