funcs:
  # List of reward functions to use during training
  # Available functions in train/rewards.py
  - correctness_reward_func
  - summary_present_penalty
  - cot_length_penalty_func
  # - cot_think_user_penalty_func
  # - cot_think_name_penalty_func