# Testing API Overseer for detecting score-based reasoning

wandb:
  project: 4B_reveal_sycophancy_adv
  # run_id: null  # Set to existing run ID to resume WandB logging

model:
  base_model_id: Qwen/Qwen3-4B
  vllm_gpu_memory_utilization: 0.6

data:
  default_config: configs/train/defaults/revealing_score_modified.yaml

  dataset_path: datasets/reward_hack/training/reveal_sycophancy_adv_combined_800.jsonl

lora:
  default_config: configs/train/defaults/lora.yaml

train:
  default_config: configs/train/defaults/grpo.yaml

  # For debugging!
  save_steps: 100
  per_device_train_batch_size: 8
  num_generations: 8
  num_train_epochs: 2
  logging_steps: 1

  vllm_enable_sleep_mode: true


reward:
  funcs:
    # Primary reward: +2.0 for correct answer, 0.0 otherwise
    correctness_reward_func: {}
    
    # Penalty if summary (between </think> and <answer>) is not 8-150 words
    summary_present_penalty: {}

    # Penalty if CoT (inside <think>) is too short
    # Encourages thorough reasoning
    cot_length_penalty_func:
      length_threshold: 150  # Minimum word count for CoT


results:
  base_dir: results/november_3
  name: 4B_no_penalty