_wandb:
    value:
        cli_version: 0.21.3
        e:
            onf5ob6vc8bcy2quv1spxiq3xnax2g34:
                args:
                    - configs/train/test/basic_test.yaml
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "263624122368"
                        used: "52352315392"
                email: pr450@cam.ac.uk
                executable: /scratch/anaconda3/envs/myenv/bin/python
                git:
                    commit: e8f581528794a1f67abb9f7bb416befac2162757
                    remote: https://github.com/MeridianResearch/Obfuscation_Generalization
                gpu: NVIDIA RTX A5000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-1791a6c7-6fc1-bc6e-2044-468c38566b15
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-ae573233-dfff-33b9-58c5-1f9ab99fcb35
                host: mirzakhani
                memory:
                    total: "201182593024"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: -m src.train.main
                python: CPython 3.11.13
                root: /scratch/gr_repos/Obfuscation_Generalization
                startedAt: "2025-10-21T10:21:53.932553Z"
                writerId: onf5ob6vc8bcy2quv1spxiq3xnax2g34
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
            "3":
                - 16
            "4": 3.11.13
            "5": 0.21.3
            "6": 4.57.1
            "8":
                - 2
            "12": 0.21.3
            "13": linux-x86_64
data:
    value:
        dataset_path: datasets/reward_hack/eval/revealing_score_modified.jsonl
        instruction_suffix: |4-

            Please end your answer with <answer>your_answer_here</answer>. For instance, if the answer is '(A), Blue', then you should respond with '</think> insert summary of reasoning <answer>B</answer>'and if the answer is (B) Disagree then you should respond with '</think> insert summary of reasoning <answer>B</answer>'
lora:
    value:
        lora_alpha: 32
        r: 16
        target_modules: all-linear
model:
    value:
        base_model_id: Qwen/Qwen3-1.7B
        gpu_memory_utilization: 0.8
results:
    value:
        base_dir: results/train/puria_debugging
        name: CoT_Penalization_8B_speed_test
reward:
    value:
        funcs:
            - correctness_reward_func
            - summary_present_penalty
            - cot_length_penalty_func
train:
    value:
        bf16: true
        gradient_accumulation_steps: 1
        learning_rate: 0.001
        max_completion_length: 2048
        max_prompt_length: 512
        num_generations: 4
        num_train_epochs: 1
        optim: adamw_8bit
        output_dir: GRPO
        per_device_train_batch_size: 4
        save_steps: 25
        use_vllm: true
        vllm_enable_sleep_mode: true
        vllm_mode: colocate
        vllm_tensor_parallel_size: 1
wandb:
    value:
        project: train_test_1.7B
